[package]
name = "fizzyhex/attributes"
description = "A wrapper for attributes with prefab functionality."
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
