gitRepoUrl = "https://github.com/Fizzyhex/CrustUtil" # From Git
gitSourceBranch = "main"

changelog = true

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "A collection of general purpose Roblox modules"