[package]
name = "fizzyhex/instance-filters"
description = "A useful collection of filters for Roblox instances."
version = "0.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
