[package]
name = "fizzyhex/baseline"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A powerfully simple module loading library."

[dependencies]
