[package]
name = "virshal/uicomponent"
description = "A library for creating GUIs"
version = "0.1.0"
license = "MIT"
authors = ["Virshal"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
